USE [master]
GO
/****** Object:  Database [parks]    Script Date: 07/05/2015 13:03:35 ******/
CREATE DATABASE [parks]
GO
ALTER DATABASE [parks] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [parks].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [parks] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [parks] SET ANSI_NULLS OFF
GO
ALTER DATABASE [parks] SET ANSI_PADDING OFF
GO
ALTER DATABASE [parks] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [parks] SET ARITHABORT OFF
GO
ALTER DATABASE [parks] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [parks] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [parks] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [parks] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [parks] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [parks] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [parks] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [parks] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [parks] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [parks] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [parks] SET  DISABLE_BROKER
GO
ALTER DATABASE [parks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [parks] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [parks] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [parks] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [parks] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [parks] SET READ_COMMITTED_SNAPSHOT ON
GO
ALTER DATABASE [parks] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [parks] SET  READ_WRITE
GO
ALTER DATABASE [parks] SET RECOVERY FULL
GO
ALTER DATABASE [parks] SET  MULTI_USER
GO
ALTER DATABASE [parks] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [parks] SET DB_CHAINING OFF
GO
